# Generated by Django 5.0 on 2024-11-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmueble', '0002_alter_comuna_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunaregion', to='gestion_inmueble.region'),
        ),
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together={('id_comuna', 'region')},
        ),
    ]
