# Generated by Django 5.0 on 2024-11-27 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmueble', '0003_alter_comuna_region_alter_comuna_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_inmueble',
            fields=[
                ('codigo_tipo_inmueble', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_inmueble', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('codigo_tipo_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipo_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmueble.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id_inmueble', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_inmueble', models.TextField()),
                ('descripcion', models.CharField(max_length=200)),
                ('m2_construido', models.FloatField()),
                ('numero_banos', models.IntegerField(default=1)),
                ('numero_hab', models.IntegerField(default=1)),
                ('direccion', models.CharField(max_length=200)),
                ('id_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmueble.comuna')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmueble.profile')),
                ('id_tipo_inmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmueble.tipo_inmueble')),
            ],
        ),
    ]
