# Generated by Django 5.1.2 on 2024-12-03 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmueble', '0007_alter_inmueble_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2024, 12, 3, 22, 53, 51, 59216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ultima_modificacion',
            field=models.DateField(default=datetime.datetime(2024, 12, 3, 22, 53, 51, 59216, tzinfo=datetime.timezone.utc)),
        ),
    ]
