# Generated by Django 5.1.2 on 2024-12-11 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
