# Generated by Django 5.0 on 2024-11-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafionew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleseccion',
            name='fecha_alta',
            field=models.DateField(),
        ),
    ]
