# Generated by Django 5.0 on 2024-11-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafionew', '0002_alter_detalleseccion_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleseccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleseccion',
            unique_together={('seccion', 'estudiante')},
        ),
    ]
