# Generated by Django 5.1.2 on 2024-11-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafionew', '0004_alter_seccion_profesor_alter_seccion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('curso', 'profesor', 'id')},
        ),
    ]
