# Generated by Django 5.1.2 on 2024-11-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafionew', '0005_alter_seccion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleseccion', to='desafionew.seccion'),
        ),
    ]
