# Generated by Django 5.1.2 on 2024-11-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafionew', '0007_alter_detalleseccion_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleseccion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantedetalleseccion', to='desafionew.estudiante'),
        ),
    ]
