# Generated by Django 5.1.2 on 2024-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=50)),
            ],
        ),
    ]
