# Generated by Django 5.0 on 2024-11-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorlibro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='autorlibro',
            name='libro',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='AutorLibro',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
